name: CI

on: [push]

jobs:
  setup-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run setup.sh
      run: |
        ls
        # TIPS: don't use yes command since it causes long execution in container
        make setup-mac
