name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run setup.sh
      run: |
        ls
        # for not having prompt when overwriting .zshrc
        rm ~/.zshrc
        ./setup.sh
