name: CI

on: [pull_request]

jobs:
  setup-mac:
    runs-on: macOS-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
    - uses: actions/checkout@v1
    - name: Run setup.sh
      run: |
        # TIPS: don't use yes command since it causes long execution in container
        make setup-mac-personal
