name: Check downloader.sh

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - "downloader.sh"

jobs:
  run-downloader:
    runs-on: ubuntu-latest
    steps:
      - name: Run downloader
        run: |
          /bin/bash -c "$(curl -fsSL "https://raw.githubusercontent.com/go-zen-chu/dotfiles/refs/heads/${{ github.head_ref }}/downloader.sh")"
