name: Check downloader.sh

on:
  pull_request:
    branches:
      - master
      - main
  push:
    paths:
      - "downloader.sh"

jobs:
  run-downloader:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: Run downloader
        run: |
          /bin/bash -c "$(curl -fsSL "https://raw.githubusercontent.com/go-zen-chu/dotfiles/refs/heads/master/downloader.sh")"
  slack-notification:
    needs: [run-downloader]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send data to Slack webhook (on failure)
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
