name: Check backup.sh

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - "backup.sh"

jobs:
  run-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run backup
        run: |
          mkdir cloudstorage
          ./backup.sh -p ./cloudstorage
          ls -alR ./cloudstorage
        env:
          # for tput coloring
          TERM: xterm-color
